<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array/>
	<key>name</key>
	<string>Python Django (Extended)</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>\b(BASE_DIR|MIDDLEWARE|ALLOWED_HOSTS|TEMPLATES|WSGI_APPLICATION|DATABASES|AUTH_PASSWORD_VALIDATORS|USE_L10N|USE_TZ|STATIC_URL|PRODUCTION_BASE_PATH|STATIC_ROOT|STATICFILES_DIRS)\b</string>
			<key>name</key>
			<string>variable.other.django.settings</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(HttpResponse(Redirect)?|render|request|response)\b</string>
			<key>name</key>
			<string>support.function.django.view</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(debug_view|hdbg|console|default_browser_language_detector|fix_turkish_chars_for_slugify)\b</string>
			<key>name</key>
			<string>support.function.django.custom</string>
		</dict>
		<dict>
			<key>include</key>
			<string>source.python.django</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.python.django-extended</string>
	<key>uuid</key>
	<string>8722BA61-ECB0-487E-9937-2D12310D4CBD</string>
</dict>
</plist>
